### ISSUE TITLE
Time for 1.2 release?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/compliance-masonry#273] opened 2018-04-04 20:07 UTC
Thanks to @rogeruiz, 1.1.3 was released that fixes the OSX issues (ref https://github.com/opencontrol/compliance-masonry/issues/271#issuecomment-378721108). 

Given there are ~130 commits since the last feature release, is it time to create compliance-masonry v1.2?

Doing local builds (RHEL + OSX) seems to work... not sure if there is a formal release testing plan. Happy to make the release, but wanted to ask first.

**Comment by afeld** [comment] 2018-04-04 20:17
Duplicate of #264 - let's continue convo there.

**Closed by afeld** 2018-04-04 20:17 UTC
