### ISSUE TITLE
Explanation of OpenControl dependency rules

### ISSUE THREAD

**Issue by gregelin** [opencontrol/compliance-masonry#231] opened 2016-10-16 20:54 UTC
Does documentation exist explaining the dependency rules in OpenControl?

- Is there a maximum level of recursion?
- Can the target repo listed as a dependencies > standard itself refer to another dependency standard, or must the target repo always have a standard file (e.g., dependencies must resolve at listed dependent repo?
- Can an local directory in a repo for a component contain an `opencontrol.yaml` file that points elsewhere?
- How are circular dependencies addressed?
- What happens if dependency is not available, or target repo is private?

**Comment by gregelin** [comment] 2016-10-16 20:55
@afeld @mogul I'm looking for documentation on OpenControl dependency rules:

Does documentation exist explaining the dependency rules?

- Is there a maximum level of recursion?
- Can the target repo listed as a dependencies > standard itself refer to another dependency standard, or must the target repo always have a standard file (e.g., dependencies must resolve at listed dependent repo?
- Can an local directory in a repo for a component contain an opencontrol.yaml file that points elsewhere?
- How are circular dependencies addressed?
- What happens if dependency is not available, or target repo is private?

**Comment by jcscottiii** [comment] 2016-10-16 21:11
- `Is there a maximum level of recursion?`
  - There is no maximum level of recursion at the moment.
- `Can the target repo listed as a dependencies > standard itself refer to another dependency standard, or must the target repo always have a standard file (e.g., dependencies must resolve at listed dependent repo?`
  - It _should_ be the former. I think I've done this before but can verify tomorrow.
- `Can an local directory in a repo for a component contain an opencontrol.yaml file that points elsewhere`?
  - Right now, it has to be in a subdirectory from the location of the `opencontrol.yaml`
- How are circular dependencies addressed?
  - Right now there is a trivial [Resource Map](https://github.com/opencontrol/compliance-masonry/blob/6513ee265cf7886e7ead1096d478e9fd93dd0a41/commands/get/resources/getter.go#L113) in which all resources have to reserve a space (using the resource type and resource name). If it can't reserve a space due to it already being occupied, it'll fail. This could be improved.
- What happens if dependency is not available, or target repo is private?
  - Not sure about the unavailable and private scenarios, but I think it would just fail (not sure if it would be a gracious error). I can test this out later. Technically, if you specify your dependencies with the `ssh` variation (and not https), it should continue but haven't tested that out yet.

**Comment by afeld** [comment] 2016-10-18 13:12
I'm going to close this since it the issue isn't necessarily actionable, but feel free to a) continue the discussion and b) reopen (or make more specific issues) around things that need to be added to the documentation, etc.

**Closed by afeld** 2016-10-18 13:12 UTC
Labels: question

**Comment by gregelin** [comment] 2016-10-19 21:38
@jcscottiii Thanks for the detailed response.

The link was useful and helped me see a bit better how Compliance-Masonry is doing lookups
