### ISSUE TITLE
Freedonia does not work

### ISSUE THREAD

**Issue by git-ingham** [opencontrol/compliance-masonry#331] opened 2018-09-24 17:01 UTC
The Freedonia example does not work as the documentation says:
```
$ git clone https://github.com/opencontrol/freedonia-aws-compliance.git
Cloning into 'freedonia-aws-compliance'...
remote: Counting objects: 94, done.
remote: Total 94 (delta 0), reused 0 (delta 0), pack-reused 94
Unpacking objects: 100% (94/94), done.
$ cd freedonia-aws-compliance/
$ compliance-masonry get
Compliance Dependencies Installed
$ compliance-masonry docs gitbook FedRAMP-low
An error occurred: Error: `opencontrols/certifications` directory does exist
$ compliance-masonry docs gitbook LATO
An error occurred: Error: `opencontrols/certifications` directory does exist
$ rpm -qa '*masonry*'
compliance-masonry-1.1.5-1.x86_64
```

**Comment by git-ingham** [comment] 2018-09-27 21:45
Thanks for the reply.  Changing URLs and trying, I get the following:
```
$ git clone https://github.com/opencontrol/freedonia-compliance
Cloning into 'freedonia-compliance'...
remote: Enumerating objects: 247, done.
remote: Total 247 (delta 0), reused 0 (delta 0), pack-reused 247
Receiving objects: 100% (247/247), 1.25 MiB | 1.87 MiB/s, done.
Resolving deltas: 100% (121/121), done.
$ cd freedonia-compliance/
$ compliance-masonry get
ERROR: Duplicate key './certifications/FredRAMP-low.yaml' in opencontrol.yaml
$ find . -name opencontrol.yaml -print | xargs grep FredRAMP-low.yaml
$ find . -type f -print | xargs grep FredRAMP-low.yaml
$ find . -name FredRAMP-low.yaml
./opencontrols/certifications/FredRAMP-low.yaml
$
```
So, where is the duplicate reference hiding?

**Comment by git-ingham** [comment] 2018-09-27 21:55
One other note.  At the end of the Freedonia README.md, it says:
`Please open issues at the ATO1Day Project, instead of within this repository.`
The link to the ATO1DayProject is 404.

**Comment by redhatrises** [comment] 2018-09-28 16:50
Thanks @git-ingham. This is a known issue. Check out https://github.com/opencontrol/freedonia-frist/issues/3

**Comment by pburkholder** [comment] 2018-09-28 22:52
Hi --I'm the main contributor to Freedonia, and I may actually have time to work on it in the coming weeks. Question is: should we keep it or deprecate it?

I created it so I could better understand myself how the controls came together as someone who was totally unfamiliar with FISMA. Does it still have instructive value in that regard?

**Comment by shawndwells** [comment] 2018-09-29 00:33
As evident by this ticket, people still use it! Seems worthwhile to update vs deprecate :)

**Comment by shawndwells** [comment] 2018-09-29 00:34
There's been updates to various tooling (masonry, fedramp templater) and content (e.g. ComplianceAsCode) that should make the examples more clear. 

@pburkholder if you've time to work on updating, that'd be really useful.

**Comment by git-ingham** [comment] 2018-09-29 16:51
compliance-masonry seems like a perfect fit for one of my customers.  However, I have yet to be able to get it to work for them.  Different parts seem to be in different states, and it is unclear what is old (and abandoned?) and what is still current.  There are still pointers to Freedonia, and having a simple example that works would be really helpful.  If not Freedonai, then other good, clear examples that work with the current (? I have the RPM installed, is it current?) version would be really useful.

**Comment by shawndwells** [comment] 2018-10-01 04:28
@git-ingham there's been a lot of movement in the past few months and documentation updates have lagged. If you're willing, could you share what challenges you're trying to solve? This would give useful input into what the docs should look like, and we'd be able to get you up & running along the way.

**Comment by METomasik** [comment] 2018-10-01 13:35
@git-ingham 

Read this comment: 

https://github.com/opencontrol/compliance-masonry/issues/332#issuecomment-424795974

This should help you solve your issue.

Mark

**Comment by METomasik** [comment] 2018-10-01 13:37
@git-ingham 

Just in case you are still looking for the link to the ATO-in-day project (though I seriously doubt it):

https://github.com/pburkholder/ato1day-compliance

**Comment by git-ingham** [comment] 2018-10-02 20:13
@shawndwells My current status is that compliance masonry looks perfect for a project I have, and I am trying to learn enough to get it to work on a toy system that I create first, then scale it up to a real system.  

I thought I would start by exploring a working small system.  What would be most helpful to me would be for the README.md at the various project pages be current so what it says actually works.  Also, remove pointers to old examples if they are not maintained (it sounds like Freedonia might get updated, which would be great).

So, at the moment, I need to first be able to get something working.  I am about to try the pointers earlier in this thread and see where I end up.

Where should I post questions or issues?  I tried this one:
https://github.com/opencontrol/schemas/issues/79
and heard nothing but crickets.  Did I post it in the wrong place?

**Comment by git-ingham** [comment] 2018-10-04 22:19
@shawndwells Thanks!

**Comment by tankcdr** [comment] 2019-02-14 21:02
I realize this thread is a little old. However I started with the Freedonia sample also. I do not have the same issues above, except that the freedonia-aws-compliance controls do not seem to be "honored" - ie 

```
systems:
     - url: https://github.com/opencontrol/freedonia-aws-compliance/
       revision: master
```
I do not see any error messages....perhaps the YAML format changed? Or is this a result of schema version mismatch? Trying to understand if there is anything to be done or if I should just abandon using freedonia.

Using compliance-masonry v 1.1.5 on OSX.

**Comment by shawndwells** [comment] 2019-02-15 00:15
@tankcdr can you share your opencontrol.yaml? will allow us to try and reproduce.

**Comment by tankcdr** [comment] 2019-02-16 15:08
@shawndwells Please see the opencontrol.yaml below:

```
schema_version: "1.0.0"
name: freedonia.fd
metadata:
  description: hello_world
  maintainers:
    - pburkholder@pobox.com
components:
  - ./AU_policy
dependencies:
  standards:
    - url: https://github.com/opencontrol/freedonia-frist/
      revision: master
  certifications:
    - url: https://github.com/opencontrol/freedonia-frist/
      revision: master
  systems:
    - url: https://github.com/opencontrol/aws-compliance/
      revision: master
```

**Comment by tankcdr** [comment] 2019-02-19 15:10
I noticed today that the repo has been updated. Freedonia is working!

**Comment by redhatrises** [comment] 2019-02-19 18:02
Yes. The issue is because of duplicate keys in the opencontrol.yaml files. Closing as this should be fixed now. Please reopen if not.

**Closed by redhatrises** 2019-02-19 18:02 UTC
