### ISSUE TITLE
Possible issue V1.1.4 - Duplicate key results from calling same dependency repository

### ISSUE THREAD

**Issue by gregelin** [opencontrol/compliance-masonry#339] opened 2019-02-18 22:02 UTC
Error using v1.1.4. See below:

```bash
Gregs-MacBook-Pro:freedonia-compliance greg$ compliance-masonry -v
masonry version: 1.1.4, build: 8cf30c64110a719c53f169b5ac0415bd23f920dc, date: 2018-06-21T22:53:56Z

Gregs-MacBook-Pro:freedonia-compliance greg$ pwd
/codedata/code/ssp-every-week/r&d/freedonia-compliance
Gregs-MacBook-Pro:freedonia-compliance greg$ compliance-masonry get
ERROR: Duplicate key './certifications/FredRAMP-low.yaml' in opencontrol.yaml

Gregs-MacBook-Pro:freedonia-compliance greg$ cat opencontrol.yaml 
schema_version: "1.0.0"
name: freedonia.fd
metadata:
  description: hello_world
  maintainers:
    - pburkholder@pobox.com
components:
  - ./AU_policy
dependencies:
  standards:
    - url: https://github.com/opencontrol/freedonia-frist/
      revision: master
  certifications:
    - url: https://github.com/opencontrol/freedonia-frist/
      revision: master
  systems:
    - url: https://github.com/opencontrol/freedonia-aws-compliance/
      revision: master
Gregs-MacBook-Pro:freedonia-compliance greg$ cat ../freedonia-frist/opencontrol.yaml 
schema_version: "1.0.0"
name: FRIST-800-53 Standards and FredRAMP Certs"
metadata:
  description: "FRIST Standards and Certs"
  maintainers:
    - pburkholder@pobox.com
standards:
  - ./standards/FRIST-800-53.yaml
certifications:
  - ./certifications/FredRAMP-low.yaml
Gregs-MacBook-Pro:freedonia-compliance greg$ # Could the issue be calling "freedonia-frist" twice?
```

**Comment by redhatrises** [comment] 2019-02-18 22:22
> Could the issue be calling "freedonia-frist" twice?

@gregelin the issue is because `FredRAMP-low.yaml` certifications is specified twice. Once in the freedonia-compliance opencontrol.yaml and the second time in freedonia-frist opencontrol.yaml.
Remove the one in freedonia-compliance, and it will work.

**Comment by redhatrises** [comment] 2019-03-11 15:28
Closing as this was a correct error due to a duplicate key in the content. Please reopen if you disagree.

**Closed by redhatrises** 2019-03-11 15:28 UTC
